"""create diagnostics tables

Revision ID: 7efa6085b98e
Revises: c9fa9050e3fe
Create Date: 2026-08-25 05:09:17.037635

"""
from alembic import op
import sqlalchemy as sa


revision = '7efa6085b98e'
down_revision = 'c9fa9050e3fe'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diagnostic_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('subject', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diagnostic_sessions_user_id'), 'diagnostic_sessions', ['user_id'], unique=False)
    op.create_table('diagnostic_answers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.String(length=64), nullable=False),
    sa.Column('answer', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['diagnostic_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diagnostic_answers_session_id'), 'diagnostic_answers', ['session_id'], unique=False)
    op.create_table('diagnostic_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('topic', sa.String(length=128), nullable=False),
    sa.Column('ability_score', sa.Float(), nullable=False),
    sa.Column('weak', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['diagnostic_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diagnostic_results_session_id'), 'diagnostic_results', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_diagnostic_results_session_id'), table_name='diagnostic_results')
    op.drop_table('diagnostic_results')
    op.drop_index(op.f('ix_diagnostic_answers_session_id'), table_name='diagnostic_answers')
    op.drop_table('diagnostic_answers')
    op.drop_index(op.f('ix_diagnostic_sessions_user_id'), table_name='diagnostic_sessions')
    op.drop_table('diagnostic_sessions')
    # ### end Alembic commands ###
