"""create knowledge_state table

Revision ID: 9d291e2f68eb
Revises: bc34a22e96af
Create Date: 2026-09-11 17:52:53.725850

"""
from alembic import op
import sqlalchemy as sa


revision = '9d291e2f68eb'
down_revision = 'bc34a22e96af'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_state',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('subject', sa.String(length=32), nullable=False),
    sa.Column('topic', sa.String(length=128), nullable=False),
    sa.Column('ability_score', sa.Float(), nullable=False),
    sa.Column('attempts_count', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'subject', 'topic', name='uq_knowledge_state_user_subject_topic')
    )
    op.create_index(op.f('ix_knowledge_state_user_id'), 'knowledge_state', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_knowledge_state_user_id'), table_name='knowledge_state')
    op.drop_table('knowledge_state')
    # ### end Alembic commands ###
