"""add parental consent fields to users

Revision ID: bc34a22e96af
Revises: 53d8369f1115
Create Date: 2026-09-07 07:41:28.884655

"""
from alembic import op
import sqlalchemy as sa


revision = 'bc34a22e96af'
down_revision = '53d8369f1115'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'users',
        sa.Column('parental_consent_given', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.add_column('users', sa.Column('parental_consent_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'parental_consent_at')
    op.drop_column('users', 'parental_consent_given')
    # ### end Alembic commands ###
