"""create trainer tables

Revision ID: c9fa9050e3fe
Revises: dff6639b499e
Create Date: 2026-08-24 14:20:39.695800

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'c9fa9050e3fe'
down_revision = 'dff6639b499e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trainer_tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('subject', sa.String(length=32), nullable=False),
    sa.Column('topic', sa.String(length=128), nullable=False),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('options', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('correct_answer', sa.String(length=255), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task_attempts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('submitted_answer', sa.String(length=255), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['trainer_tasks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_attempts_task_id'), 'task_attempts', ['task_id'], unique=False)
    op.create_index(op.f('ix_task_attempts_user_id'), 'task_attempts', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_attempts_user_id'), table_name='task_attempts')
    op.drop_index(op.f('ix_task_attempts_task_id'), table_name='task_attempts')
    op.drop_table('task_attempts')
    op.drop_table('trainer_tasks')
    # ### end Alembic commands ###
